### ISSUE TITLE
Convert agent to a CustomResource 

### ISSUE THREAD

**Issue by LiliC** [weaveworks/launcher#245]
By converting the agent part of the launcher to be deployed as a [`CustomResource`](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/) we can pass arguments and options via the [`CustomResourceDefinition`](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#customresourcedefinitions) and with that also solve https://github.com/weaveworks/launcher/issues/145.

Besides the configurations we would also solve the problem of just applying the manifest file every X amount of time, but instead we would watch and react on events, e.g. when a `Secret` gets deleted we would update the resources, similiar to how we already do for the cloudwatch in the agents.

We could still keep the bootstrap part of the launcher and in it generate the `CRD` manifest file needed to deploy the agent `CR` (`weave-cloud-operator` :) ). So the install part would be the same as now, if we want to, e.g. via the curl command and the helm option could remain as well. But the `weave-cloud-operator` could also be installed and configured with a standalone manifest file in the users cluster.

The https://github.com/operator-framework might be useful IMO in this case to generate things needed to convert the launcher/agent into an "operator".

cc @bricef @marccarre @dlespiau @leth

**Comment by LiliC** [comment]
Example manifest file for `WeaveCloud` CRD:

```
apiVersion: cloud.weave.works/v1beta1
kind: WeaveCloud
metadata:
  name: weave-cloud
  namespace: weave
spec:
    image: weaveworks/agents:12345
    general:
      kubernetes-version: 1.10.0
      env: gke
      cloudwatch:
        aws-region: west-1
        aws-secret: foo
        aws-resource: foo,bar
        aws-config: bar
    flux:
      config:
        git-label: label
        git-url: url
        git-path: path
        git-branch: branch
    scope:
      container-runtime-endpoint: /var/run/crio.sock
      kubernetes-probe: true
    cortex:
      example: foo-config 
```
